---
    name: Checks

    on:
      push:
        branches:
          - main # Adjust the branch as needed
    
    jobs:
      test-lint:
        name: Test and Lint
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v2
    
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USER }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
    
          - name: Set up Docker Compose
            run: docker-compose up -d
    
          - name: Test
            run: docker-compose exec app sh -c "python manage.py test"
    
          - name: Lint
            run: docker-compose exec app sh -c "flake8"
    
